$(document).ready(function(){if(localStorage.getItem('checkout')==null){localStorage.setItem('checkout',0)}
$("#checkout").html(localStorage.getItem('checkout'));var loggedin=localStorage.getItem('loggedIn');if(loggedin==1){$("#loginlogout").html("Logout");$("#accountdetails").removeClass("d-none");$("#accountdetails").removeClass("show")}else{$("#accountdetails").addClass("d-none");$("#loginlogout").html("Login");$("#loginlogout").prop("href","login.html")}
if(localStorage.getItem('userdetails')===null){var userDetails={firstName:"Nissa",lastName:"Revane",dob:"1993-01-01",address1:"Bala Ged",address2:"Zendikar",address3:"Zendikar"};localStorage.setItem('userdetails',JSON.stringify(userDetails))}else{userDetails=JSON.parse(localStorage.getItem('userdetails'))}
if($('#udetails').length>0){$('input[name="firstname"]').val(userDetails.firstName);$('input[name="lastname"]').val(userDetails.lastName);$('input[name="dob"]').val(userDetails.dob);$('input[name="address1"]').val(userDetails.address1);$('input[name="address2"]').val(userDetails.address2);$('input[name="address3"]').val(userDetails.address3)}
$("#loginlogout").button().click(function(){if(loggedin==1){localStorage.setItem('loggedIn',0);window.location.href="login.html"}else window.location.href="login.html"});$('form[name="login"]').submit(function(event){var email=$('input[name="email"]').val();var password=$('input[name="password"]').val();if(email=="nissa@zendikar.com"&&password=="password"){localStorage.setItem('loggedIn',1);window.location.href="shop.html"}else{localStorage.setItem('loggedIn',0);$("#loginerror").addClass("d-block")}
return!1});$('form[name="userdetails"]').submit(function(event){userDetails.firstName=$('input[name="firstname"]').val();userDetails.lastName=$('input[name="lastname"]').val();userDetails.address1=$('input[name="address1"]').val();userDetails.address2=$('input[name="address2"]').val();userDetails.address3=$('input[name="address3"]').val();localStorage.setItem('userdetails',JSON.stringify(userDetails));return!1});$('form[name="paymentdetails"]').submit(function(event){var cardnumber=$('input[name="cardnumber"]').val();if(cardnumber=="1234 5678 9102 3456"){$("#payment-failure").addClass("d-none");$("#payment-success").removeClass("d-none");$("#buy-button").addClass("d-none");var total=0;localStorage.setItem('checkout',total);$("#checkout").html(total)}else{$("#payment-failure").removeClass("d-none")}
return!1});$(".addtocart").click(function(){var total=localStorage.getItem('checkout');total++;localStorage.setItem('checkout',total);$("#checkout").html(total)})});var totalCheckout=(localStorage.setItem("total",0));function AddProduct1(){localStorage.setItem("product1Called","true");localStorage.setItem('title1','Core 2021 Boosters');localStorage.setItem('price1',3.99);localStorage.setItem("total",totalCheckout+4)}
function AddProduct2(){localStorage.setItem("product2Called","true");localStorage.setItem('title2','Final Adventure Challenger Deck');localStorage.setItem('price2',24.99);localStorage.setItem("total",totalCheckout+25)}
function AddProduct3(){localStorage.setItem("product3Called","true");localStorage.setItem('title3','Timeless Wisdom');localStorage.setItem('price3',40.00);localStorage.setItem("total",totalCheckout+40)}
function ShowBasket(){var itemDets=document.createElement('p');itemDets.classList.add('text-white');itemDets.innerText='Total : '+parseInt(localStorage.getItem("total"));if(localStorage.getItem("product1Called")=="true"){var itemsContainer=document.getElementById('itemsContainer');itemsContainer.appendChild(itemDets);itemDets.innerText+='\n'+localStorage.getItem('title1');itemDets.innerText+=' -  €'+localStorage.getItem('price1')}
if(localStorage.getItem("product2Called")=="true"){itemDets.innerText+='\n'+localStorage.getItem('title2');itemDets.innerText+=' -  €'+localStorage.getItem('price2')}
if(localStorage.getItem("product3Called")=="true"){itemDets.innerText+='\n'+localStorage.getItem('title3');itemDets.innerText+=' -  €'+localStorage.getItem('price3')}}
function showMessage(){var alert=document.getElementById('alertSent');alert.classList.remove('d-none');alert.classList.add('d-block')}